import { ClerkProvider } from "@clerk/nextjs";
import type { Metadata } from "next";
import { ToastContainer } from "react-toastify";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <ClerkProvider>
        <body className="font-primary">
          {children}
          <ToastContainer
            autoClose={2000}
            className="text-sm font-medium"
            position="top-right"
          />
        </body>
      </ClerkProvider>
    </html>
  );
}
